apiVersion: apps/v1
kind: Deployment
metadata:
  name: watson-nlp-container
spec:
  selector:
    matchLabels:
      app: watson-nlp-container
  replicas: 1
  template:
    metadata:
      labels:
        app: watson-nlp-container
    spec:
      containers:
      - name: watson-nlp-container
        image: us.icr.io/watson-core-demo/watson-nlp-container:v1
        env:
          - name: ACCEPT_LICENSE
            value: true
        ports:
        - containerPort: 8085
      serviceAccount: watson-nlp-sa
---
apiVersion: v1
kind: Service
metadata:
  name: watson-nlp-container
spec:
  type: ClusterIP
  selector:
    app: watson-nlp-container
  ports:
  - port: 8085
    protocol: TCP
    targetPort: 8085
