apiVersion: apps/v1
kind: Deployment
metadata:
  name: watson-nlp-container
spec:
  selector:
    matchLabels:
      app: watson-nlp-container
  replicas: 1
  template:
    metadata:
      labels:
        app: watson-nlp-container
    spec:
      containers:
      - name: watson-nlp-container
        image: image-registry.openshift-image-registry.svc:5000/openshift/watson-nlp-container:v1
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: watson-nlp-container
spec:
  type: ClusterIP
  selector:
    app: watson-nlp-container
  ports:
  - port: 8085
    protocol: TCP
    targetPort: 8085