apiVersion: apps/v1
kind: Deployment
metadata:
  name: watson-nlp-runtime
spec:
  selector:
    matchLabels:
      app: watson-nlp-runtime
  replicas: 1
  template:
    metadata:
      labels:
        app: watson-nlp-runtime
    spec:
      initContainers:
      - name: ensemble-model
        image: <REGISTRY>/<NAMESPACE>/watson-nlp_ensemble_model:v1 
        volumeMounts:
        - name: model-directory
          mountPath: "/app/models"
        env:
        - name: ACCEPT_LICENSE
          value: 'true'
      containers:
      - name: watson-nlp-runtime
        image: wcp-ai-foundation-team-docker-virtual.artifactory.swg-devops.com/watson-nlp-runtime:1.0.0
        env:
        - name: ACCEPT_LICENSE
          value: 'true'
        - name: LOCAL_MODELS_DIR
          value: "/app/models"
        - name: LOG_LEVEL
          value: debug
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
        ports:
        - containerPort: 8080
        - containerPort: 8085
        volumeMounts:
        - name: model-directory
          mountPath: "/app/models"
      imagePullSecrets:
      - name: watson-nlp
      volumes:
      - name: model-directory
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: watson-nlp-runtime-service
spec:
  type: ClusterIP
  selector:
    app: watson-nlp-runtime
  ports:
  - port: 8080
    name: http-rest-svc
    protocol: TCP
    targetPort: 8080
  - port: 8085
    name: http-grpc-svc
    protocol: TCP
    targetPort: 8085
  
