apiVersion: apps/v1
kind: Deployment
metadata:
  name: dash-app-grpc
spec:
  selector:
    matchLabels:
      app: dash-app-grpc
  replicas: 1
  template:
    metadata:
      labels:
        app: dash-app-grpc
    spec:
      containers:
      - name: dash-app-grpc
        image: image-registry.openshift-image-registry.svc:5000/openshift/dash-app-grpc:2022083111
        env:
          - name: TONE_CLASSIFICATION_STOCK_MODEL
            valueFrom:
              configMapKeyRef:
                key: TONE_CLASSIFICATION_STOCK_MODEL
                name: dashapp-config
          - name: GRPC_SERVER_URL
            valueFrom:
              configMapKeyRef:
                key: GRPC_SERVER_URL
                name: dashapp-config
          - name: SYNTAX_IZUMO_EN_STOCK_MODEL
            valueFrom:
              configMapKeyRef:
                key: SYNTAX_IZUMO_EN_STOCK_MODEL
                name: dashapp-config
          - name: NLP_MODEL_SERVICE_TYPE
            valueFrom:
              configMapKeyRef:
                key: NLP_MODEL_SERVICE_TYPE
                name: dashapp-config
        ports:
        - containerPort: 8050